import { Button } from "@/common/components/ui/button"
import type { RegisterEventResponse } from "@/modules/registration/service/register-event"
import { QRCodeSVG } from "qrcode.react"

type TicketCardProps = {
	ticket: RegisterEventResponse
	adminLabel?: boolean
}

export function RegisterTicketCard({ ticket, adminLabel }: TicketCardProps) {
	return (
		<div className="relative z-1 flex w-full flex-col-reverse justify-between gap-6 rounded-2xl border border-neutral-700 bg-primary-950/50 px-8 py-8 backdrop-blur-2xl lg:flex-row lg:px-16 print:border-0 print:bg-neutral-100">
			<div className="flex flex-col gap-4">
				{adminLabel && (
					<div className="w-fit rounded bg-brand-700 px-4 py-2 text-center font-medium text-white text-xs">
						GENERATED BY ADMIN ON {new Date().toLocaleDateString()}
					</div>
				)}
				<div className="flex flex-col">
					<span className="font-semibold text-title-1 text-white md:text-header lg:text-display print:text-neutral-900">
						SAN 2025 E-Ticket
					</span>
					<span className="text-headline text-neutral-400 lg:text-title-2">
						{ticket.event_participant_details
							.map((event) => event.event_type.name)
							.join(", ")}
					</span>
				</div>
				<div className="grid w-full max-w-md grid-cols-1 gap-2 text-body text-white md:grid-cols-2 lg:text-headline print:text-neutral-900">
					<span className="font-semibold">Name</span>
					<span>{ticket.name}</span>
					<span className="font-semibold">Email</span>
					<span>{ticket.email}</span>
					<span className="font-semibold">Phone Number</span>
					<span>{ticket.phone_number}</span>
				</div>
			</div>
			<div className="flex flex-col gap-4">
				<div className="flex flex-col items-center gap-3 rounded-xl border border-brand-700 p-4 print:border-0 print:bg-brand-700/10">
					<QRCodeSVG
						value={ticket.id}
						size={300}
						className="w-full rounded-xl bg-white p-8"
					/>
					<span className="text-center text-neutral-400 print:text-brand-700">
						Please show this ticket to staff in registry
					</span>
				</div>
				<Button
					type="button"
					className="print:hidden"
					onClick={() => {
						window.print()
					}}
				>
					Download
				</Button>
			</div>
		</div>
	)
}
